/*
	NOMBRE:		Gerardo Josue Montoya Amaya
	Nº.CUENTA:	20191002364
*/

------CREACION DEL SCHEMA---------
CREATE SCHEMA gjma

------ SE CREAN PRIMERO LAS TABLAS QUE NO TIENEN DEPENDENCIAS DE OTRAS, SEGUIDAMENTE EL RESTO------------

CREATE TABLE gjma.HOTEL (
	CODIGO INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(60) NOT NULL,
	DIRECCION NVARCHAR (200) NOT NULL
)


CREATE TABLE gjma.AEROLINEA(
	CODIGO INTEGER IDENTITY(1,1) PRIMARY KEY,
	DESCUENTO FLOAT NOT NULL,
	CHECK(DESCUENTO>=10)
)

CREATE TABLE gjma.BOLETO(
	CODIGO INTEGER IDENTITY(1,1) PRIMARY KEY,
	CODIGOA INTEGER NOT NULL,
	NO_VUELO INTEGER NOT NULL,
	FECHA DATE,
	DESTINO VARCHAR(100) NOT NULL,
	constraint FK_AEROLINEA_CODIGO foreign key (CODIGOA) references gjma.AEROLINEA(CODIGO),
	CHECK(DESTINO='Mexico' or DESTINO='Guatemala' or DESTINO='Panamá')
)

CREATE TABLE gjma.CLIENTE(
	IDENTIDAD NVARCHAR (13) PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(60) NOT NULL,
	TELEFONO NVARCHAR(30) NOT NULL,
	CODIGOB INTEGER NOT NULL
	constraint FK_BOLETO_CODIGO foreign key (CODIGOB) references gjma.BOLETO(CODIGO)

)

CREATE TABLE gjma.RESERVAS(
	IDENTIDAD NVARCHAR (13) NOT NULL,
	CODIGO INTEGER NOT NULL,
	FECHA_IN DATE,
	FECHA_OUT DATE,
	CANTIDAD_PERSONAS INTEGER DEFAULT 0 NOT NULL,
	constraint FK_CLIENTE_IDENTIDAD foreign key (IDENTIDAD) references gjma.CLIENTE(IDENTIDAD),
	constraint FK_HOTEL_CODIGO foreign key (CODIGO) references gjma.HOTEL(CODIGO),
	PRIMARY KEY (IDENTIDAD,CODIGO)
)

SELECT * FROM gjma.AEROLINEA


SELECT * FROM gjma.HOTEL


SELECT * FROM gjma.BOLETO


SELECT * FROM gjma.CLIENTE


SELECT * FROM gjma.RESERVAS
