    
SET SERVEROUTPUT ON;    

/*
Gerardo Josue Montoya Amaya
20191002364
*/

/*EJERCICIO #1*/
DECLARE
    NOMBRE VARCHAR2(100);
    APELLIDO1 VARCHAR2(100);
    APELLIDO2 VARCHAR2(100);
BEGIN
    DBMS_OUTPUT.put_line('--------EJERCICIO 1--------');
    NOMBRE:='gerardo';
    APELLIDO1:='montoya';
    APELLIDO2:='amaya';
    DBMS_OUTPUT.put_line(CONCAT(CONCAT(CONCAT(SUBSTR(INITCAP(NOMBRE),1,1),'.'),CONCAT(SUBSTR(INITCAP(APELLIDO1),1,1),'.')),SUBSTR(INITCAP(APELLIDO2),1,1)));
END;

/

/*EJERCICIO #2*/

DECLARE
    NUM1 NUMBER;
BEGIN
    DBMS_OUTPUT.put_line('-------EJERCICIO 2-------');
    NUM1:=79;
    IF( MOD(NUM1,2)=0) then
        DBMS_OUTPUT.put_line('Es PAR');
    ELSE
        DBMS_OUTPUT.put_line('Es IMPAR');
    end IF;
END;

/

/*EJERCICIO #3*/
DECLARE
    SALARIO_MAXIMO NUMBER;
BEGIN
    DBMS_OUTPUT.put_line('-----EJERCICIO 3---------');
    SELECT 
        MAX(SALARY) INTO SALARIO_MAXIMO 
    FROM employees
    WHERE department_id=100;
    DBMS_OUTPUT.put_line(SALARIO_MAXIMO);
END;

/

/*EJERCICIO #4*/

DECLARE
    DEPT DEPARTMENTS.DEPARTMENT_ID%TYPE;
    DEPTN VARCHAR2(100);
    NUMEMPL NUMBER;
BEGIN
    DBMS_OUTPUT.put_line('------EJERCICIO 4-------');
    DEPT:= 10;
    SELECT DEPARTMENT_NAME INTO DEPTN FROM departments WHERE department_id=DEPT;
    SELECT COUNT(EMPLOYEE_ID) INTO NUMEMPL FROM employees WHERE department_id=DEPT GROUP BY department_id;
    DBMS_OUTPUT.put_line(CONCAT(CONCAT(DEPTN,' '),NUMEMPL));
END;

/

/*EJERCICIO #5*/

DECLARE
    SAL_MAX NUMBER;
    SAL_MIN NUMBER;
    DIFERENCIA NUMBER;
BEGIN
    DBMS_OUTPUT.put_line('--------EJERCICIO 5--------');
    SELECT MAX(SALARY) INTO SAL_MAX FROM EMPLOYEES;
    SELECT MIN(SALARY) INTO SAL_MIN FROM EMPLOYEES;
    DIFERENCIA:= SAL_MAX-SAL_MIN;
    DBMS_OUTPUT.put_line(CONCAT('EL SALARIO MAXIMO ES:',SAL_MAX));
    DBMS_OUTPUT.put_line(CONCAT('EL SALARIO MINIMO ES:',SAL_MIN));
    DBMS_OUTPUT.put_line(CONCAT('LA DIFERENCIA ES    :',DIFERENCIA));
END;


    